export const adminConst = {
    ADMIN_LOGIN_LOADING:"ADMIN_LOGIN_LOADING",
    ADMIN_LOGIN_SUCCESS:"ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGIN_ERROR:"ADMIN_LOGIN_ERROR",
    ADMIN_HEADER_RQ:"ADMIN_HEADER_RQ",
    ADMIN_HEADER_RJ:"ADMIN_HEADER_RJ",
    ADMIN_HEADER_SC:"ADMIN_HEADER_SC",
}