export const quoteDirectoryConst = {
    QUOTED_LOADING:"QUOTED_LOADING",
    QUOTED_DELETED_LOADING:"QUOTED_DELETED_LOADING",
    QUOTED_SUCCESS:"QUOTED_SUCCESS",
    QUOTED_DELETED_SUCCESS:"QUOTED_DELETED_SUCCESS",
    QUOTED_ERROR:"QUOTED_ERROR",    
    SINGLE_QUOTE_LOADING:"SINGLE_QUOTE_LOADING",
    SINGLE_QUOTE_SUCCESS:"SINGLE_QUOTE_SUCCESS",
    SINGLE_QUOTE_ERROR:"SINGLE_QUOTE_ERROR"
}